[supervisord]
nodaemon=true

[program:apache2]
command=apache2-foreground
autostart=true
autorestart=true

[program:laravel-setup]
command=bash -c "php artisan migrate:fresh --seed --force && php artisan storage:link"
autostart=true
autorestart=false
